name: flutter_advanced_reference
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #State Management
  flutter_bloc: ^8.1.5
  #Code Generation (Mainly used with cubit and retrofit)
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  #Automatic generate code for converting from json by annotation and json_serializable
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  #Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1
  #Localization
  intl: ^0.18.1
  easy_localization: ^3.0.7
  #for splash screen
  flutter_native_splash: ^2.3.7
  #An SVG rendering library for Flutter
  flutter_svg: ^2.0.10+1
  #for screen size
  flutter_screenutil: ^5.9.0








dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/
